# Generated by Django 4.2.27 on 2025-12-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_label',
            field=models.CharField(blank=True, help_text='Klassi nimetus, mida õpetaja õpetab või kuhu õpilane kuulub', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('counselor', 'Counselor'), ('student', 'Student')], default='teacher', max_length=20),
        ),
    ]
